# Copyright Bosch Software Innovations GmbH, 2016.
# Part of the SW360 Portal Project.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html

version: '2'
services:
  sw360cvesearchBase:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: sw360cvesearch
    restart: unless-stopped
    environment:
      - REDIS_HOST=sw360redis
      - MONGODB_HOST=sw360mongodb
