# Copyright Bosch Software Innovations GmbH, 2016.
# Part of the SW360 Portal Project.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html

version: '2'
services:
  sw360:
    environment:
      - POSTGRES_PASSWORD=sw360fossy
      - COUCHDB_PASSWORD=sw360fossy

      ## the following is also set in `docker-compose.cve-search-server.yml`
      # - CVE_SEARCH_HOST=https://cve.circl.lu/

      ## $HTTPS_HOSTS should be a comma seperated list if `host:port` pairs, e.g.
      # - HTTPS_HOSTS=some.bdp_host.org:443,an.ldaps.host:636

      ## the variable $LDAP_CONFIGURATION can contain the full LDAP configuration
      ## and will be appended to portal-ext.properties. It can be defined in the
      ## following way: 
      # - |
      #   LDAP_CONFIGURATION=
      #   ldap.auth.enabled=true
      #   ldap.password.policy.enabled=true
      #
      #   ldap.server.ids=0
      #   ldap.server.name.0=LdapServer
      #
      #   ldap.base.provider.url.0=ldap://10.1.2.100:389
      #   ldap.base.dn.0=ou=Users,o=Example
      #   ldap.security.principal.0=LDAP1,ou=Users,o=Example
      #   ldap.security.credentials.0=Password
      #
      #   ldap.auth.search.filter.0=(&(objectCategory=person)(mail=@email_address@))
      #   ldap.import.user.search.filter.0=(objectClass=person)
      #   ldap.import.group.search.filter.0=(objectClass=group)
      #
      #   ldap.user.mappings.0=uuid=uuid\nscreenName=name\npassword=unicodePwd\nemailAddress=mail\nfirstName=givenName\nmiddleName=middleName\nlastName=sn\nfullName=cn\njobTitle=title\ngroup=memberOf
      #   ldap.user.custom.mappings.0=organization=department
      #   ldap.group.mappings.0=groupName=cn\ndescription=description\nuser=member
      #
      #   ldap.import.enabled=false
      #   ldap.import.on.startup=false
    volumes:
      - ./_deploy:/opt/sw360/deploy
      - ./_logs:/opt/sw360/logs

  sw360postgres:
    environment:
      - POSTGRES_PASSWORD=sw360fossy

  sw360couchdb:
    environment:
     - COUCHDB_PASSWORD=sw360fossy
    volumes:
      - ./_couchdb:/usr/local/var/lib/couchdb


  ##############################################################################    
  ## used by cve-search (see docker-compose.cve-search-server.yml)
  sw360mongodb:
    volumes:
      - ./_mongodb:/data/db
